namespace: dev

backend:
  image: nimamrze/fullstack-fastapi-backend
  tag: dev
  replicas: 1
  port: 8000

frontend:
  image: nimamrze/fullstack-fastapi-frontend
  tag: dev
  replicas: 1
  port: 80

ingress:
  host: dev.services-cloud.abrdns.com

secret:
  postgresPassword: postgres
  firstSuperuserPassword: admin123
  secretKey: dev-secret-key

database:
  host: postgres-dev-postgresql
