namespace: prod

backend:
  image: nimamrze/fullstack-fastapi-backend
  tag: dev
  replicas: 2
  port: 8000

frontend:
  image: nimamrze/fullstack-fastapi-frontend
  tag: dev
  replicas: 2
  port: 80

ingress:
  host: prod.services-cloud.abrdns.com

secret:
  postgresPassword: prod-postgres-password
  firstSuperuserPassword: prod-admin-password
  secretKey: prod-secret-key-change-me

database:
  host: postgres-prod-postgresql
