apiVersion: v1
kind: ConfigMap
metadata:
  name: fullstack-fastapi-config
  namespace: {{ .Values.namespace }}
data:
  PROJECT_NAME: "Full Stack FastAPI"
  ENVIRONMENT: "local"
  BACKEND_CORS_ORIGINS: "http://localhost,http://frontend"
  POSTGRES_SERVER: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "admin123"
  SECRET_KEY: "dev-secret-key"
