apiVersion: v1
kind: ConfigMap
metadata:
  name: fullstack-fastapi-config
  namespace: {{ .Values.namespace }}
data:
  PROJECT_NAME: "Full Stack FastAPI"
  ENVIRONMENT: "local"
  BACKEND_CORS_ORIGINS: "http://localhost,http://frontend"
  POSTGRES_SERVER: "{{ .Values.database.host }}"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  POSTGRES_USER: "postgres"
  FIRST_SUPERUSER: "admin@example.com"
