apiVersion: v1
kind: Secret
metadata:
  name: fullstack-fastapi-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secret.postgresPassword }}"
  FIRST_SUPERUSER_PASSWORD: "{{ .Values.secret.firstSuperuserPassword }}"
  SECRET_KEY: "{{ .Values.secret.secretKey }}"
